name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Build docker image
        run: docker build -t ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }} .
      - uses: rlespinasse/release-that@v1.x
        with:
          without-prefix: true
          github-token: ${{ secrets.GH_TOKEN }}
